################################
#                              #
# Default Configuration        #
#                              #
################################

baseurl: http://heavyn-and-rocky.weditorials.co.nz

title: Heavyn and Rocky | Weditorials Wedding Photography
subtitle: A Weditorials Photography Creation
seo:
  description: "Welcome to the wedding of Heavyn and Rocky."
  keywords: ["wedding photography", "engagement photography"]

assets: /assets
css:    /assets/css
js:     /assets/js
img:    /assets/img
audio:  /assets/audio

################################
#                              #
# Default Settings             #
#                              #
################################

# where to read the files from
source:      ./
# where to put rendered site source
destination: ./_site
# where the layouts can the found
layouts:     ./_layouts
includes:     ./_includes
timezone:     Pacific/Auckland

future:      true
show_drafts: false
# removes the .html from rendered pages
# eg. /contact.html becomes /contact/
permalink: pretty
# requires rdiscount gem
# markdown: rdiscount

exclude: [CNAME,Gemfile,Gemfile.lock,Procfile,README.md,bower.json,config.rb,glare,gulpfile.js,jekyll,node_modules,package.json,refresh.sh,sample-page]

################################
#                              #
# Author Configuration         #
#                              #
################################

author:
  name:    Sergei Filippov
  email:   s@haiku.co.nz
  github:  sergeifilippov
  twitter: sergeifilippov
  company:
    name:   Haiku Lab Limited
    url:    http://haiku.co.nz
    github: haikulab

################################
#                              #
# Google Analytics             #
#                              #
################################

google_analytics_tracking_id:
google_analytics_tracking_domain: weditorials.co.nz

################################
#                              #
# Social                       #
#                              #
################################

facebook: "https://www.facebook.com/weditorialsnz/"
instagram: "http://instagram.com/alyssajouk/"
pinterest: "http://www.pinterest.com/weditorials/"

################################
#                              #
# Facebool: Open Graph         #
#                              #
################################

## found in _includes/facebook_og.html
# og_url: {{site.baseurl}}
# og_image: {{site.img}}/weditorials_facebook.jpg

og_description: Heavyn and Rocky Wedding Photos by Weditorial.co.nz
og_type:        website
og_title:       Heavyn and Rocky Wedding Photos by Weditorial.co.nz
og_site_name:   Heavyn and Rocky Wedding Photos by Weditorial.co.nz

################################
#                              #
# Audio                        #
#                              #
################################

song:
  autoplay: true
  filename: frankie_valli_-_can_t_take_my_eyes_off_you.mp3
